### PR TITLE
Ukrainian translation for *.js files...

### PR DESCRIPTION
**Pull request by fordnn**
... has been added.

### CODE REVIEW

**Comment by iJungleboy** [comment]
This is almost correct - I'll accept the pull-request and then fix it. what is wrong is:
1. you should change the original json-files - the .js get auto-created by the grunt-scripts

**Comment by iJungleboy** [comment]
Awesome - thank you very much :)!

**Comment by iJungleboy** [comment]
thanks a ton - already merged into 2sxc, should be part of 08.00.07 :)

**Comment by fordnn** [comment]
np, you are welcome! Always glad to help :)

**Pull request merged**
